// Thin re-export barrel - all logic now lives in services/actions/ modules
export type { ExecutionContext, ActionResult } from './actions/index.js';
export {
  replacePlaceholders,
  getClientData,
  sleep,
  executeSendEmail,
  executeSendSms,
  executeGenerateLetter,
  executeCommunicationAction,
  executeCreateTask,
  executeCompleteTask,
  executeAssignTask,
  executeTaskAction,
  executeUpdateClientStatus,
  executeAddTag,
  executeRemoveTag,
  executeAssignClient,
  executeClientAction,
  executeUpdateDocumentStatus,
  executeRequestDocument,
  executeDocumentAction,
  executeCallWebhook,
  executeWebhookAction,
  executeCreateNote,
  executeNoteAction,
  executeSendNotification,
  executeLogActivity,
  executeNotificationAction,
  executeWait,
  executeBranch,
  executeParallel,
  executeFlowControlAction,
} from './actions/index.js';